// /src/utils/mealPlanSelector.js

// Mocked meal plans
// /src/utils/mealPlanData.js

import { exercisePlans } from '../utils/exercisePlanData';

export const mealPlans = {
  HTN_Male_Obese: [
    {
      day: "Sunday",
      breakfast: "Oatmeal with berries",
      lunch: "Grilled salmon + quinoa",
      snack: "Almonds",
      dinner: "Baked chicken + brown rice",
      calories: "1600 kcal",
    },
    {
      day: "Monday",
      breakfast: "Greek yogurt + banana",
      lunch: "Turkey sandwich + salad",
      snack: "Baby carrots + hummus",
      dinner: "Baked tilapia + steamed veggies",
      calories: "1550 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Scrambled eggs",
      lunch: "Grilled chicken wrap",
      snack: "Greek yogurt",
      dinner: "Lentil soup + whole grain bread",
      calories: "1500 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Low-fat cottage cheese + pineapple",
      lunch: "Veggie stir-fry + tofu",
      snack: "Pumpkin seeds",
      dinner: "Baked cod + sweet potato",
      calories: "1580 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Whole grain toast + peanut butter",
      lunch: "Chicken Caesar salad",
      snack: "Edamame",
      dinner: "Grilled shrimp + wild rice",
      calories: "1570 kcal",
    },
    {
      day: "Friday",
      breakfast: "Smoothie with spinach and banana",
      lunch: "Bean burrito",
      snack: "Fruit bowl",
      dinner: "Stir-fried tofu + veggies",
      calories: "1550 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Whole grain cereal + low-fat milk",
      lunch: "Quinoa and black bean salad",
      snack: "Yogurt parfait",
      dinner: "Baked chicken + roasted vegetables",
      calories: "1580 kcal",
    },
  ],

  HTN_Male_NonObese: [
    {
      day: "Sunday",
      breakfast: "Oatmeal + walnuts",
      lunch: "Grilled chicken breast + quinoa",
      snack: "Almonds",
      dinner: "Broiled fish + brown rice",
      calories: "1500 kcal",
    },
    {
      day: "Monday",
      breakfast: "Greek yogurt + mixed berries",
      lunch: "Turkey wrap + spinach salad",
      snack: "Baby carrots",
      dinner: "Baked cod + roasted veggies",
      calories: "1450 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Scrambled egg whites + veggies",
      lunch: "Veggie stir-fry + brown rice",
      snack: "Pumpkin seeds",
      dinner: "Grilled shrimp tacos",
      calories: "1470 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Whole wheat toast + peanut butter",
      lunch: "Lentil soup + salad",
      snack: "Fruit smoothie",
      dinner: "Baked chicken thighs",
      calories: "1490 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Smoothie with protein powder",
      lunch: "Chicken Caesar salad",
      snack: "Trail mix",
      dinner: "Tilapia + steamed vegetables",
      calories: "1480 kcal",
    },
    {
      day: "Friday",
      breakfast: "Yogurt + granola",
      lunch: "Tuna salad sandwich",
      snack: "Apple slices",
      dinner: "Stir-fried tofu + veggies",
      calories: "1460 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Steel-cut oats + berries",
      lunch: "Quinoa and black bean bowl",
      snack: "Nuts and raisins",
      dinner: "Grilled chicken + vegetables",
      calories: "1500 kcal",
    },
  ],

  HTN_Female_Obese: [
    {
      day: "Sunday",
      breakfast: "Smoothie with spinach and berries",
      lunch: "Salmon salad",
      snack: "Greek yogurt",
      dinner: "Baked chicken breast",
      calories: "1500 kcal",
    },
    {
      day: "Monday",
      breakfast: "Greek yogurt + flaxseeds",
      lunch: "Turkey lettuce wrap",
      snack: "Baby carrots + hummus",
      dinner: "Grilled tilapia",
      calories: "1450 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Oatmeal + banana",
      lunch: "Quinoa salad",
      snack: "Almonds",
      dinner: "Vegetable stir-fry",
      calories: "1400 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Cottage cheese + strawberries",
      lunch: "Chicken Caesar salad",
      snack: "Pumpkin seeds",
      dinner: "Lentil soup",
      calories: "1450 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Egg white omelet + veggies",
      lunch: "Tuna salad",
      snack: "Fruit bowl",
      dinner: "Baked cod + broccoli",
      calories: "1480 kcal",
    },
    {
      day: "Friday",
      breakfast: "Peanut butter on whole grain toast",
      lunch: "Bean burrito",
      snack: "Yogurt parfait",
      dinner: "Stir-fried tofu",
      calories: "1470 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Whole wheat pancakes + berries",
      lunch: "Grilled chicken sandwich",
      snack: "Mixed nuts",
      dinner: "Baked salmon + asparagus",
      calories: "1500 kcal",
    },
  ],

  HTN_Female_NonObese: [
    {
      day: "Sunday",
      breakfast: "Oatmeal + chia seeds",
      lunch: "Grilled chicken salad",
      snack: "Fruit smoothie",
      dinner: "Broiled fish + vegetables",
      calories: "1400 kcal",
    },
    {
      day: "Monday",
      breakfast: "Greek yogurt + walnuts",
      lunch: "Veggie wrap",
      snack: "Baby carrots",
      dinner: "Baked tilapia",
      calories: "1350 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Smoothie + protein powder",
      lunch: "Quinoa and vegetable bowl",
      snack: "Pumpkin seeds",
      dinner: "Grilled shrimp",
      calories: "1380 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Whole wheat toast + peanut butter",
      lunch: "Chicken Caesar salad",
      snack: "Almonds",
      dinner: "Lentil soup",
      calories: "1400 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Low-fat yogurt + fruit",
      lunch: "Tuna sandwich",
      snack: "Fruit bowl",
      dinner: "Stir-fried tofu",
      calories: "1380 kcal",
    },
    {
      day: "Friday",
      breakfast: "Cottage cheese + pineapple",
      lunch: "Black bean salad",
      snack: "Mixed nuts",
      dinner: "Baked cod + vegetables",
      calories: "1390 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Whole grain cereal + milk",
      lunch: "Veggie stir fry",
      snack: "Edamame",
      dinner: "Grilled chicken breast",
      calories: "1400 kcal",
    },
  ],
  DM_Male_Obese: [
    {
      day: "Sunday",
      breakfast: "Oatmeal with chia seeds",
      lunch: "Grilled chicken + quinoa",
      snack: "Almonds",
      dinner: "Baked salmon + spinach",
      calories: "1600 kcal",
    },
    {
      day: "Monday",
      breakfast: "Greek yogurt + walnuts",
      lunch: "Turkey wrap + mixed greens",
      snack: "Baby carrots",
      dinner: "Tilapia + roasted vegetables",
      calories: "1550 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Smoothie with protein powder",
      lunch: "Lentil salad",
      snack: "Apple slices",
      dinner: "Baked chicken thighs",
      calories: "1500 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Scrambled eggs + whole grain toast",
      lunch: "Veggie stir fry",
      snack: "Pumpkin seeds",
      dinner: "Grilled shrimp + wild rice",
      calories: "1580 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Cottage cheese + berries",
      lunch: "Quinoa black bean bowl",
      snack: "Trail mix",
      dinner: "Baked cod + broccoli",
      calories: "1570 kcal",
    },
    {
      day: "Friday",
      breakfast: "Smoothie + spinach",
      lunch: "Chicken Caesar salad",
      snack: "Greek yogurt",
      dinner: "Stir-fried tofu + vegetables",
      calories: "1550 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Whole grain pancakes",
      lunch: "Veggie wrap",
      snack: "Fruit bowl",
      dinner: "Grilled chicken breast + salad",
      calories: "1580 kcal",
    },
  ],

  DM_Male_NonObese: [
    {
      day: "Sunday",
      breakfast: "Oatmeal + flaxseeds",
      lunch: "Grilled salmon + asparagus",
      snack: "Almonds",
      dinner: "Baked chicken + quinoa",
      calories: "1500 kcal",
    },
    {
      day: "Monday",
      breakfast: "Low-fat yogurt + fruit",
      lunch: "Turkey lettuce wrap",
      snack: "Baby carrots",
      dinner: "Tilapia + sweet potatoes",
      calories: "1450 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Smoothie + berries",
      lunch: "Quinoa salad",
      snack: "Walnuts",
      dinner: "Baked cod + veggies",
      calories: "1480 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Scrambled egg whites + spinach",
      lunch: "Chicken stir fry",
      snack: "Pumpkin seeds",
      dinner: "Grilled shrimp tacos",
      calories: "1490 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Greek yogurt + almonds",
      lunch: "Black bean bowl",
      snack: "Trail mix",
      dinner: "Grilled tofu + rice",
      calories: "1480 kcal",
    },
    {
      day: "Friday",
      breakfast: "Smoothie with protein powder",
      lunch: "Chicken salad",
      snack: "Fruit bowl",
      dinner: "Lentil soup + bread",
      calories: "1460 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Steel-cut oats",
      lunch: "Veggie burrito",
      snack: "Mixed nuts",
      dinner: "Baked chicken + roasted vegetables",
      calories: "1500 kcal",
    },
  ],

  DM_Female_Obese: [
    {
      day: "Sunday",
      breakfast: "Smoothie with berries",
      lunch: "Grilled salmon salad",
      snack: "Greek yogurt",
      dinner: "Baked chicken breast",
      calories: "1500 kcal",
    },
    {
      day: "Monday",
      breakfast: "Cottage cheese + pineapple",
      lunch: "Turkey wrap",
      snack: "Baby carrots",
      dinner: "Baked tilapia",
      calories: "1450 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Oatmeal + banana",
      lunch: "Quinoa salad",
      snack: "Almonds",
      dinner: "Vegetable stir-fry",
      calories: "1400 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Greek yogurt + granola",
      lunch: "Chicken Caesar salad",
      snack: "Pumpkin seeds",
      dinner: "Lentil soup",
      calories: "1450 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Egg white omelet + veggies",
      lunch: "Tuna salad",
      snack: "Fruit bowl",
      dinner: "Baked cod + green beans",
      calories: "1480 kcal",
    },
    {
      day: "Friday",
      breakfast: "Whole grain toast + peanut butter",
      lunch: "Black bean burrito",
      snack: "Yogurt parfait",
      dinner: "Stir-fried tofu",
      calories: "1470 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Whole wheat pancakes + berries",
      lunch: "Chicken sandwich",
      snack: "Mixed nuts",
      dinner: "Baked salmon + broccoli",
      calories: "1500 kcal",
    },
  ],

  DM_Female_NonObese: [
    {
      day: "Sunday",
      breakfast: "Oatmeal + chia seeds",
      lunch: "Grilled chicken salad",
      snack: "Fruit smoothie",
      dinner: "Broiled fish + veggies",
      calories: "1400 kcal",
    },
    {
      day: "Monday",
      breakfast: "Greek yogurt + almonds",
      lunch: "Veggie wrap",
      snack: "Baby carrots",
      dinner: "Baked tilapia",
      calories: "1350 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Smoothie with spinach",
      lunch: "Quinoa vegetable bowl",
      snack: "Pumpkin seeds",
      dinner: "Grilled shrimp",
      calories: "1380 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Whole wheat toast + peanut butter",
      lunch: "Chicken Caesar salad",
      snack: "Almonds",
      dinner: "Lentil soup",
      calories: "1400 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Low-fat yogurt + fruit",
      lunch: "Tuna sandwich",
      snack: "Fruit bowl",
      dinner: "Stir-fried tofu",
      calories: "1380 kcal",
    },
    {
      day: "Friday",
      breakfast: "Cottage cheese + strawberries",
      lunch: "Black bean salad",
      snack: "Mixed nuts",
      dinner: "Baked cod + veggies",
      calories: "1390 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Whole grain cereal + milk",
      lunch: "Veggie stir-fry",
      snack: "Edamame",
      dinner: "Grilled chicken breast",
      calories: "1400 kcal",
    },
  ],
  Cholesterol_Male_Obese: [
    {
      day: "Sunday",
      breakfast: "Oatmeal with walnuts",
      lunch: "Grilled chicken + quinoa",
      snack: "Almonds",
      dinner: "Baked salmon + asparagus",
      calories: "1600 kcal",
    },
    {
      day: "Monday",
      breakfast: "Greek yogurt + flaxseeds",
      lunch: "Turkey wrap + salad",
      snack: "Baby carrots",
      dinner: "Tilapia + steamed broccoli",
      calories: "1550 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Smoothie with spinach",
      lunch: "Lentil salad",
      snack: "Apple slices",
      dinner: "Grilled shrimp + wild rice",
      calories: "1520 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Scrambled eggs + avocado toast",
      lunch: "Veggie stir fry",
      snack: "Pumpkin seeds",
      dinner: "Baked cod + sweet potato",
      calories: "1580 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Cottage cheese + berries",
      lunch: "Quinoa black bean bowl",
      snack: "Trail mix",
      dinner: "Grilled chicken breast + brown rice",
      calories: "1570 kcal",
    },
    {
      day: "Friday",
      breakfast: "Smoothie + banana",
      lunch: "Chicken Caesar salad",
      snack: "Greek yogurt",
      dinner: "Stir-fried tofu + vegetables",
      calories: "1550 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Whole grain pancakes + blueberries",
      lunch: "Veggie wrap",
      snack: "Fruit bowl",
      dinner: "Baked salmon + roasted vegetables",
      calories: "1580 kcal",
    },
  ],

  Cholesterol_Male_NonObese: [
    {
      day: "Sunday",
      breakfast: "Oatmeal + chia seeds",
      lunch: "Grilled salmon + green beans",
      snack: "Almonds",
      dinner: "Baked chicken + sweet potato",
      calories: "1500 kcal",
    },
    {
      day: "Monday",
      breakfast: "Greek yogurt + berries",
      lunch: "Turkey sandwich",
      snack: "Baby carrots",
      dinner: "Tilapia + brown rice",
      calories: "1450 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Smoothie + spinach",
      lunch: "Quinoa vegetable salad",
      snack: "Pumpkin seeds",
      dinner: "Grilled shrimp",
      calories: "1480 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Scrambled eggs + toast",
      lunch: "Vegetable stir fry",
      snack: "Fruit smoothie",
      dinner: "Lentil soup + bread",
      calories: "1490 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Low-fat cottage cheese + pineapple",
      lunch: "Black bean burrito",
      snack: "Trail mix",
      dinner: "Grilled tofu",
      calories: "1480 kcal",
    },
    {
      day: "Friday",
      breakfast: "Peanut butter toast",
      lunch: "Chicken salad",
      snack: "Mixed nuts",
      dinner: "Stir-fried shrimp",
      calories: "1460 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Whole grain cereal + milk",
      lunch: "Veggie wrap",
      snack: "Fruit bowl",
      dinner: "Grilled chicken + vegetables",
      calories: "1500 kcal",
    },
  ],

  Cholesterol_Female_Obese: [
    {
      day: "Sunday",
      breakfast: "Smoothie + berries",
      lunch: "Grilled salmon salad",
      snack: "Greek yogurt",
      dinner: "Baked chicken breast",
      calories: "1500 kcal",
    },
    {
      day: "Monday",
      breakfast: "Cottage cheese + pineapple",
      lunch: "Turkey lettuce wrap",
      snack: "Baby carrots",
      dinner: "Baked tilapia",
      calories: "1450 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Oatmeal + banana",
      lunch: "Quinoa salad",
      snack: "Almonds",
      dinner: "Vegetable stir fry",
      calories: "1400 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Greek yogurt + granola",
      lunch: "Chicken Caesar salad",
      snack: "Pumpkin seeds",
      dinner: "Lentil soup",
      calories: "1450 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Egg white omelet + veggies",
      lunch: "Tuna salad",
      snack: "Fruit bowl",
      dinner: "Baked cod + broccoli",
      calories: "1480 kcal",
    },
    {
      day: "Friday",
      breakfast: "Whole grain toast + peanut butter",
      lunch: "Black bean salad",
      snack: "Yogurt parfait",
      dinner: "Stir-fried tofu",
      calories: "1470 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Whole wheat pancakes + blueberries",
      lunch: "Chicken sandwich",
      snack: "Mixed nuts",
      dinner: "Baked salmon + green beans",
      calories: "1500 kcal",
    },
  ],

  Cholesterol_Female_NonObese: [
    {
      day: "Sunday",
      breakfast: "Oatmeal + chia seeds",
      lunch: "Grilled chicken salad",
      snack: "Fruit smoothie",
      dinner: "Broiled fish + vegetables",
      calories: "1400 kcal",
    },
    {
      day: "Monday",
      breakfast: "Greek yogurt + almonds",
      lunch: "Veggie wrap",
      snack: "Baby carrots",
      dinner: "Baked tilapia",
      calories: "1350 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Smoothie with spinach",
      lunch: "Quinoa bowl",
      snack: "Pumpkin seeds",
      dinner: "Grilled shrimp",
      calories: "1380 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Whole wheat toast + peanut butter",
      lunch: "Chicken Caesar salad",
      snack: "Almonds",
      dinner: "Lentil soup",
      calories: "1400 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Low-fat yogurt + fruit",
      lunch: "Tuna sandwich",
      snack: "Fruit bowl",
      dinner: "Stir-fried tofu",
      calories: "1380 kcal",
    },
    {
      day: "Friday",
      breakfast: "Cottage cheese + strawberries",
      lunch: "Black bean salad",
      snack: "Mixed nuts",
      dinner: "Baked cod + veggies",
      calories: "1390 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Whole grain cereal + milk",
      lunch: "Veggie stir fry",
      snack: "Edamame",
      dinner: "Grilled chicken breast",
      calories: "1400 kcal",
    },
  ],
  Multiple_Male_Obese: [
    {
      day: "Sunday",
      breakfast: "Oatmeal with chia seeds",
      lunch: "Grilled chicken + quinoa",
      snack: "Almonds",
      dinner: "Baked salmon + spinach",
      calories: "1600 kcal",
    },
    {
      day: "Monday",
      breakfast: "Greek yogurt + flaxseeds",
      lunch: "Turkey wrap + salad",
      snack: "Baby carrots",
      dinner: "Tilapia + roasted vegetables",
      calories: "1550 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Smoothie with spinach and berries",
      lunch: "Lentil salad",
      snack: "Apple slices",
      dinner: "Baked chicken thighs",
      calories: "1520 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Scrambled eggs + whole grain toast",
      lunch: "Veggie stir fry",
      snack: "Pumpkin seeds",
      dinner: "Grilled shrimp + wild rice",
      calories: "1580 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Cottage cheese + berries",
      lunch: "Quinoa black bean bowl",
      snack: "Trail mix",
      dinner: "Baked cod + sweet potato",
      calories: "1570 kcal",
    },
    {
      day: "Friday",
      breakfast: "Smoothie + spinach",
      lunch: "Chicken Caesar salad",
      snack: "Greek yogurt",
      dinner: "Stir-fried tofu + veggies",
      calories: "1550 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Whole grain pancakes",
      lunch: "Veggie wrap",
      snack: "Fruit bowl",
      dinner: "Baked chicken + roasted vegetables",
      calories: "1580 kcal",
    },
  ],

  Multiple_Male_NonObese: [
    {
      day: "Sunday",
      breakfast: "Oatmeal + chia seeds",
      lunch: "Grilled salmon + asparagus",
      snack: "Almonds",
      dinner: "Baked chicken + quinoa",
      calories: "1500 kcal",
    },
    {
      day: "Monday",
      breakfast: "Greek yogurt + berries",
      lunch: "Turkey lettuce wrap",
      snack: "Baby carrots",
      dinner: "Tilapia + steamed broccoli",
      calories: "1450 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Smoothie with spinach",
      lunch: "Quinoa vegetable bowl",
      snack: "Pumpkin seeds",
      dinner: "Grilled shrimp",
      calories: "1480 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Scrambled egg whites + spinach",
      lunch: "Vegetable stir fry",
      snack: "Fruit smoothie",
      dinner: "Lentil soup + bread",
      calories: "1490 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Cottage cheese + pineapple",
      lunch: "Black bean salad",
      snack: "Trail mix",
      dinner: "Grilled tofu + brown rice",
      calories: "1480 kcal",
    },
    {
      day: "Friday",
      breakfast: "Peanut butter toast",
      lunch: "Chicken salad",
      snack: "Mixed nuts",
      dinner: "Stir-fried shrimp",
      calories: "1460 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Whole grain cereal + milk",
      lunch: "Veggie stir fry",
      snack: "Fruit bowl",
      dinner: "Grilled chicken breast",
      calories: "1500 kcal",
    },
  ],

  Multiple_Female_Obese: [
    {
      day: "Sunday",
      breakfast: "Smoothie with berries",
      lunch: "Grilled salmon salad",
      snack: "Greek yogurt",
      dinner: "Baked chicken breast",
      calories: "1500 kcal",
    },
    {
      day: "Monday",
      breakfast: "Cottage cheese + pineapple",
      lunch: "Turkey lettuce wrap",
      snack: "Baby carrots",
      dinner: "Baked tilapia",
      calories: "1450 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Oatmeal + banana",
      lunch: "Quinoa salad",
      snack: "Almonds",
      dinner: "Vegetable stir fry",
      calories: "1400 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Greek yogurt + granola",
      lunch: "Chicken Caesar salad",
      snack: "Pumpkin seeds",
      dinner: "Lentil soup",
      calories: "1450 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Egg white omelet + veggies",
      lunch: "Tuna salad",
      snack: "Fruit bowl",
      dinner: "Baked cod + green beans",
      calories: "1480 kcal",
    },
    {
      day: "Friday",
      breakfast: "Whole grain toast + peanut butter",
      lunch: "Black bean salad",
      snack: "Yogurt parfait",
      dinner: "Stir-fried tofu",
      calories: "1470 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Whole wheat pancakes + blueberries",
      lunch: "Chicken sandwich",
      snack: "Mixed nuts",
      dinner: "Baked salmon + broccoli",
      calories: "1500 kcal",
    },
  ],

  Multiple_Female_NonObese: [
    {
      day: "Sunday",
      breakfast: "Oatmeal + chia seeds",
      lunch: "Grilled chicken salad",
      snack: "Fruit smoothie",
      dinner: "Broiled fish + vegetables",
      calories: "1400 kcal",
    },
    {
      day: "Monday",
      breakfast: "Greek yogurt + almonds",
      lunch: "Veggie wrap",
      snack: "Baby carrots",
      dinner: "Baked tilapia",
      calories: "1350 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Smoothie with spinach",
      lunch: "Quinoa bowl",
      snack: "Pumpkin seeds",
      dinner: "Grilled shrimp",
      calories: "1380 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Whole wheat toast + peanut butter",
      lunch: "Chicken Caesar salad",
      snack: "Almonds",
      dinner: "Lentil soup",
      calories: "1400 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Low-fat yogurt + fruit",
      lunch: "Tuna sandwich",
      snack: "Fruit bowl",
      dinner: "Stir-fried tofu",
      calories: "1380 kcal",
    },
    {
      day: "Friday",
      breakfast: "Cottage cheese + strawberries",
      lunch: "Black bean salad",
      snack: "Mixed nuts",
      dinner: "Baked cod + veggies",
      calories: "1390 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Whole grain cereal + milk",
      lunch: "Veggie stir fry",
      snack: "Edamame",
      dinner: "Grilled chicken breast",
      calories: "1400 kcal",
    },
  ],
  NoDiseases_Male_Obese: [
    {
      day: "Sunday",
      breakfast: "Oatmeal with chia seeds",
      lunch: "Grilled chicken + quinoa",
      snack: "Almonds",
      dinner: "Baked salmon + spinach",
      calories: "1600 kcal",
    },
    {
      day: "Monday",
      breakfast: "Greek yogurt + flaxseeds",
      lunch: "Turkey wrap + salad",
      snack: "Baby carrots",
      dinner: "Tilapia + roasted vegetables",
      calories: "1550 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Smoothie with spinach",
      lunch: "Lentil salad",
      snack: "Apple slices",
      dinner: "Grilled shrimp + wild rice",
      calories: "1520 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Scrambled eggs + whole grain toast",
      lunch: "Veggie stir fry",
      snack: "Pumpkin seeds",
      dinner: "Baked cod + sweet potato",
      calories: "1580 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Cottage cheese + berries",
      lunch: "Quinoa black bean bowl",
      snack: "Trail mix",
      dinner: "Grilled chicken breast + brown rice",
      calories: "1570 kcal",
    },
    {
      day: "Friday",
      breakfast: "Smoothie + banana",
      lunch: "Chicken Caesar salad",
      snack: "Greek yogurt",
      dinner: "Stir-fried tofu + vegetables",
      calories: "1550 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Whole grain pancakes + blueberries",
      lunch: "Veggie wrap",
      snack: "Fruit bowl",
      dinner: "Baked salmon + roasted vegetables",
      calories: "1580 kcal",
    },
  ],

  NoDiseases_Male_NonObese: [
    {
      day: "Sunday",
      breakfast: "Oatmeal + chia seeds",
      lunch: "Grilled salmon + green beans",
      snack: "Almonds",
      dinner: "Baked chicken + sweet potato",
      calories: "1500 kcal",
    },
    {
      day: "Monday",
      breakfast: "Greek yogurt + berries",
      lunch: "Turkey sandwich",
      snack: "Baby carrots",
      dinner: "Tilapia + brown rice",
      calories: "1450 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Smoothie with spinach",
      lunch: "Quinoa vegetable salad",
      snack: "Pumpkin seeds",
      dinner: "Grilled shrimp",
      calories: "1480 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Scrambled eggs + toast",
      lunch: "Vegetable stir fry",
      snack: "Fruit smoothie",
      dinner: "Lentil soup + bread",
      calories: "1490 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Low-fat cottage cheese + pineapple",
      lunch: "Black bean burrito",
      snack: "Trail mix",
      dinner: "Grilled tofu",
      calories: "1480 kcal",
    },
    {
      day: "Friday",
      breakfast: "Peanut butter toast",
      lunch: "Chicken salad",
      snack: "Mixed nuts",
      dinner: "Stir-fried shrimp",
      calories: "1460 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Whole grain cereal + milk",
      lunch: "Veggie wrap",
      snack: "Fruit bowl",
      dinner: "Grilled chicken + vegetables",
      calories: "1500 kcal",
    },
  ],

  NoDiseases_Female_Obese: [
    {
      day: "Sunday",
      breakfast: "Smoothie with berries",
      lunch: "Grilled salmon salad",
      snack: "Greek yogurt",
      dinner: "Baked chicken breast",
      calories: "1500 kcal",
    },
    {
      day: "Monday",
      breakfast: "Cottage cheese + pineapple",
      lunch: "Turkey lettuce wrap",
      snack: "Baby carrots",
      dinner: "Baked tilapia",
      calories: "1450 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Oatmeal + banana",
      lunch: "Quinoa salad",
      snack: "Almonds",
      dinner: "Vegetable stir fry",
      calories: "1400 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Greek yogurt + granola",
      lunch: "Chicken Caesar salad",
      snack: "Pumpkin seeds",
      dinner: "Lentil soup",
      calories: "1450 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Egg white omelet + veggies",
      lunch: "Tuna salad",
      snack: "Fruit bowl",
      dinner: "Baked cod + broccoli",
      calories: "1480 kcal",
    },
    {
      day: "Friday",
      breakfast: "Whole grain toast + peanut butter",
      lunch: "Black bean salad",
      snack: "Yogurt parfait",
      dinner: "Stir-fried tofu",
      calories: "1470 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Whole wheat pancakes + blueberries",
      lunch: "Chicken sandwich",
      snack: "Mixed nuts",
      dinner: "Baked salmon + green beans",
      calories: "1500 kcal",
    },
  ],

  NoDiseases_Female_NonObese: [
    {
      day: "Sunday",
      breakfast: "Oatmeal + chia seeds",
      lunch: "Grilled chicken salad",
      snack: "Fruit smoothie",
      dinner: "Broiled fish + vegetables",
      calories: "1400 kcal",
    },
    {
      day: "Monday",
      breakfast: "Greek yogurt + almonds",
      lunch: "Veggie wrap",
      snack: "Baby carrots",
      dinner: "Baked tilapia",
      calories: "1350 kcal",
    },
    {
      day: "Tuesday",
      breakfast: "Smoothie with spinach",
      lunch: "Quinoa bowl",
      snack: "Pumpkin seeds",
      dinner: "Grilled shrimp",
      calories: "1380 kcal",
    },
    {
      day: "Wednesday",
      breakfast: "Whole wheat toast + peanut butter",
      lunch: "Chicken Caesar salad",
      snack: "Almonds",
      dinner: "Lentil soup",
      calories: "1400 kcal",
    },
    {
      day: "Thursday",
      breakfast: "Low-fat yogurt + fruit",
      lunch: "Tuna sandwich",
      snack: "Fruit bowl",
      dinner: "Stir-fried tofu",
      calories: "1380 kcal",
    },
    {
      day: "Friday",
      breakfast: "Cottage cheese + strawberries",
      lunch: "Black bean salad",
      snack: "Mixed nuts",
      dinner: "Baked cod + veggies",
      calories: "1390 kcal",
    },
    {
      day: "Saturday",
      breakfast: "Whole grain cereal + milk",
      lunch: "Veggie stir fry",
      snack: "Edamame",
      dinner: "Grilled chicken breast",
      calories: "1400 kcal",
    },
  ],
};

/**
 * Helper function to determine disease category
 */
function determineDiseaseCategory(comorbidities) {
  if (!comorbidities || comorbidities.length === 0) return "NoDiseases";
  if (comorbidities.length > 1) return "Multiple";
  return comorbidities[0]; // HTN, DM, or Cholesterol
}

/**
 * Constructs a unique plan key based on user profile
 */
function buildPlanKey({ gender, obese, comorbidities }) {
  const diseaseCategory = determineDiseaseCategory(comorbidities);
  const obeseStatus = obese ? "Obese" : "NonObese";
  return `${diseaseCategory}_${gender}_${obeseStatus}`;
}

/**
 * Retrieves the 7-day Meal Plan based on user profile
 */
export function getMealPlan({ age, gender, obese, comorbidities }) {
  const key = buildPlanKey({ gender, obese, comorbidities });
  console.log("Meal Plan Key:", key);
  if (mealPlans[key]) {
    return mealPlans[key];
  } else {
    console.warn("No matching meal plan found, returning default.");
    return mealPlans["NoDiseases_Female_NonObese"];
  }
}

/**
 * Retrieves the Exercise Plan based on user profile
 */
export function getExercisePlan({ age, gender, obese, comorbidities }) {
  const key = buildPlanKey({ gender, obese, comorbidities });
  console.log("Exercise Plan Key:", key);
  if (exercisePlans[key]) {
    return exercisePlans[key];
  } else {
    console.warn("No matching exercise plan found, returning default.");
    return exercisePlans["NoDiseases_Female_NonObese"];
  }
}
